' Gambas module file

'Zona de constantes
Public squares As Integer = 8 'cuadros del tablero
Public initialrows As Integer = 3

Public piece As Integer = 1
Public king As Integer = 2
Public blank As Integer = 0

Public black As Integer = -1
Public white As Integer = 1

Public ColorDarkSquare As Integer = Color.gray 'black
Public ColorLightSquare As Integer = Color.orange 'red

Public colorSelect As Integer = 1 ' blue
Public ColorSelectFinal As Integer = 9 'cyan

Public ColorBlack As Integer = 8 'gray
Public colorWhite As Integer = 15 'white

Public jugando As Boolean

Public PlayerStrategy As New Collection 'estrategia de los jugadores black y white,

Public Sub iniciar()

  Constantes.jugando = False
  Constantes.ColorDarkSquare = Color.LightGray
  Constantes.ColorLightSquare = Color.Orange
  'defino estrategia de los jugadores como "Humanos"
  PlayerStrategy.Clear()
  PlayerStrategy.Add(0, Str$(black))
  PlayerStrategy.Add(0, Str$(white))
  FMain.casilla = 1 'que siempre empiece por casilla "origen"

End
